version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sqlalchemy
    versions:
    - 1.4.0
    - 1.4.1
    - 1.4.2
    - 1.4.3
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.7
    - 1.4.8
    - 1.4.9
  - dependency-name: colorlog
    versions:
    - 4.7.2
    - 4.8.0
  - dependency-name: flask-apscheduler
    versions:
    - 1.12.0
    - 1.12.1
  - dependency-name: responses
    versions:
    - 0.13.0
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: flake8-bugbear
    versions:
    - 21.3.1
    - 21.3.2
  - dependency-name: pandas
    versions:
    - 1.2.1
    - 1.2.2
    - 1.2.3
  - dependency-name: coverage
    versions:
    - "5.4"
    - "5.5"
  - dependency-name: aiohttp
    versions:
    - 3.7.4
  - dependency-name: mypy
    versions:
    - "0.812"
  - dependency-name: pika
    versions:
    - 1.2.0
  - dependency-name: xlrd
    versions:
    - 2.0.1
  - dependency-name: pymysql
    versions:
    - 1.0.2
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: eve
    versions:
    - 1.1.5
  - dependency-name: pytest-cov
    versions:
    - 2.11.1
  - dependency-name: flask-cors
    versions:
    - 3.0.10
  - dependency-name: requests
    versions:
    - 2.25.1
