version: "3.8"
services:
  lighthouse:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LOCALHOST=host.docker.internal
      - FLASK_APP=lighthouse
      - FLASK_ENV=development
      - EVE_SETTINGS=development.py

    volumes:
      - ".:/code"

    networks:
      - default
      - heron_databases_external


networks:
  heron_databases_external:
    external: true
