import os

# Database connections
LOCALHOST = os.environ.get("LOCALHOST", "localhost")

# Local
LOCAL_MYSQL_HOST = LOCALHOST
LOCAL_MLWH_DB = ""
LOCAL_MYSQL_USER = ""
LOCAL_MYSQL_PWD = ""
LOCAL_MYSQL_PORT = 1234
LOCAL_MYSQL_DB_CONN_STRING = f"{LOCAL_MYSQL_USER}:{LOCAL_MYSQL_PWD}@{LOCAL_MYSQL_HOST}:{LOCAL_MYSQL_PORT}"
LOCAL_MLWH_TABLE = ""

LOCAL_MONGO_DB_HOST=''
LOCAL_MONGO_DB = ""
LOCAL_MONGO_TABLE = ""
LOCAL_MONGO_DB_CLIENT = f"mongodb://{LOCAL_MONGO_DB_HOST}/"


# UAT
TEST_MYSQL_HOST = ""
TEST_MLWH_DB = ""
TEST_MYSQL_USER = ""
TEST_MYSQL_PWD = ""
TEST_MYSQL_PORT = 1234
TEST_MYSQL_DB_CONN_STRING = f"{TEST_MYSQL_USER}:{TEST_MYSQL_PWD}@{TEST_MLWH_DB}:{TEST_MYSQL_PORT}"
TEST_MLWH_TABLE = ""

TEST_MONGO_DB_HOST= ""
TEST_MONGO_DB_USER = ""
TEST_MONGO_DB_PASSWORD= ""
TEST_MONGO_DB = ""
TEST_MONGO_TABLE = ""
TEST_MONGO_DB_AUTH_SOURCE = ""
TEST_MONGO_DB_CLIENT = f"mongodb://{TEST_MONGO_DB_USER}:{TEST_MONGO_DB_PASSWORD}@{TEST_MONGO_DB_HOST}/"


# Prod
PROD_MYSQL_HOST = ""
PROD_MLWH_DB = ""
PROD_MYSQL_USER = ""
PROD_MYSQL_PWD = ""
PROD_MYSQL_PORT = 1234
PROD_MYSQL_DB_CONN_STRING = f"{PROD_MYSQL_USER}:{PROD_MYSQL_PWD}@{PROD_MLWH_DB}:{PROD_MYSQL_PORT}"
PROD_MLWH_TABLE = ""

PROD_MONGO_DB_HOST= ""
PROD_MONGO_DB_USER = ""
PROD_MONGO_DB_PASSWORD= ""
PROD_MONGO_DB = ""
PROD_MONGO_TABLE = ""
PROD_MONGO_DB_AUTH_SOURCE = ""
PROD_MONGO_DB_CLIENT = f"mongodb://{PROD_MONGO_DB_USER}:{PROD_MONGO_DB_PASSWORD}@{PROD_MONGO_DB_HOST}/"


# Exported / Used --------------
MYSQL_HOST = LOCAL_MYSQL_HOST
MLWH_DB = LOCAL_MLWH_DB
MYSQL_USER = LOCAL_MYSQL_USER
MYSQL_PWD = LOCAL_MYSQL_PWD
MYSQL_PORT = LOCAL_MYSQL_PORT
MYSQL_DB_CONN_STRING = LOCAL_MYSQL_DB_CONN_STRING
MLWH_TABLE = LOCAL_MLWH_TABLE

MONGO_DB_CLIENT = LOCAL_MONGO_DB_CLIENT
MONGO_DB = LOCAL_MONGO_DB
MONGO_TABLE = LOCAL_MONGO_TABLE
MONGO_DB_HOST = LOCAL_MONGO_DB_HOST
MONGO_DB_USER = ""
MONGO_DB_PASSWORD= ""
MONGO_DB_AUTH_SOURCE = ""

# Local files
fixed_data_file = ""
malformed_csv = ""
control_csv = ""
skippable_csv = ""

FIXED_DATA_COL_NAME = ""
ORIGINAL_DATA_COL_NAME = ""
MONGO_COLUMN_NAME = ""
MLWH_COLUMN_NAME = ""

# SQL calls
SQL_GET_ALL_DATA = (
    "select *"
    " from table"
)

SQL_MLWH_GET_MALFORMED_DATA = (
    "select x, y, z, root_sample_id, rna_id, lab_id, result"
    " from table"
    " where condition"
)
