name: Automated build, test, release and push

on:
  push:
    branches:
      - develop
      - master

env:
  IMAGE_NAME: ${{ github.repository }}/${{ github.event.repository.name }}

jobs:
  build_test_release_push:
    runs-on: ubuntu-18.04
    services:
      mongodb:
        image: mongo:4.2.5
        ports:
          - 27017:27017

      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: unified_warehouse_test

      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: MyS3cr3tPassw0rd

    steps:
      - uses: actions/checkout@v2

      - uses: nelonoel/branch-name@v1.0.1

      - name: Build and tag the image for testing and release
        run: >-
          docker build .
          --file Dockerfile
          --tag docker.pkg.github.com/${IMAGE_NAME}:${BRANCH_NAME}

      - name: Create SQL Server testing database
        run: >-
          docker run
          --network host
          --env EVE_SETTINGS=test.py
          --entrypoint ''
          docker.pkg.github.com/${IMAGE_NAME}:${BRANCH_NAME}
          python setup_sqlserver_test_db.py

      - name: Setup the test MLWH and Events databases
        run: >-
          docker run
          --network host
          --env EVE_SETTINGS=test.py
          --entrypoint ''
          docker.pkg.github.com/${IMAGE_NAME}:${BRANCH_NAME}
          python setup_test_db.py

      - name: Run tests against the image
        run: >-
          docker run
          --network host
          --env EVE_SETTINGS=test.py
          --entrypoint ''
          docker.pkg.github.com/${IMAGE_NAME}:${BRANCH_NAME}
          python -m pytest --no-cov -vx

      - name: Set release tag
        # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
        run: echo "RELEASE_VERSION=$(printf -- '%s%s\n' $(cat .release-version) $([ ${BRANCH_NAME} = "develop" ] && printf -- '-%s-develop' ${GITHUB_RUN_ID} || echo ""))" >> $GITHUB_ENV

      - name: Create release
        uses: ncipollo/release-action@v1.8.8
        with:
          name: ${{ env.RELEASE_VERSION }}
          tag: v${{ env.RELEASE_VERSION }}
          prerelease: ${{ !(github.ref == 'refs/heads/master') }}
          commit: ${{ github.sha }}

      - name: Login to registry
        run: >-
          docker login
          -u ${{ github.actor }}
          -p ${{ secrets.GITHUB_TOKEN }}
          docker.pkg.github.com

      - name: Tag image with release version
        run: >-
          docker tag
          docker.pkg.github.com/${IMAGE_NAME}:${BRANCH_NAME}
          docker.pkg.github.com/${IMAGE_NAME}:${{ env.RELEASE_VERSION }}

      - name: Push release tag image to registry
        run: >-
          docker push docker.pkg.github.com/${IMAGE_NAME}:${{ env.RELEASE_VERSION }}

      - name: Remove the oldest package
        # The delete-package-versions action has become broken and the fix doesn't look imminent.
        # Re-enable this later if a fix comes out! https://github.com/actions/delete-package-versions/issues/28
        if: false
        uses: actions/delete-package-versions@v1
        with:
          package-name: "${{ github.event.repository.name }}"
